- src: geerlingguy.java

- src: geerlingguy.jenkins

- src: geerlingguy.postgresql

- src: geerlingguy.sonar

- src: wtanaka.unzip

- src: savoirfairelinux.nexus3-oss

- src: geerlingguy.git

- src: tecris.maven

- src: geerlingguy.repo-epel

- src: geerlingguy.ansible