## Customize the test machine
machine:
   services:
      - docker

   # Version of ruby to use
   ruby:
      version:
         2.3.1

test:
   override:
      - >
        wget -qO- bit.ly/ansibletest | env
        DOCKER_IMAGES="debian:8 ubuntu:14.04 ubuntu:16.04 fedora:23"
        ANSIBLE_VERSIONS="1.4 1.4.4 1.5.4 1.6.1 1.7.2 1.8.4 1.9.2 2.0.0.2 2.1.0.0 2.2.1.0"
        sh
